/* 
 * Generated by ASDT 
*/ 

/*
klasse:			Fadable
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			eplus
erstellung: 		08.03.2005
zuletzt bearbeitet:	08.03.2005
durch			gj
status:			final
*/

interface com.adgamewonderland.eplus.cebit.interfaces.Fadable {
	
	function onFade(alpha:Number ):Void;
	
	function onStopFade():Void;
	
}