/* 
 * Generated by ASDT 
*/ 

/*
interface:			Strokable
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			eplus
erstellung: 		28.02.2005
zuletzt bearbeitet:	28.02.2005
durch			gj
status:			final
*/

interface com.adgamewonderland.eplus.cebit.interfaces.Strokable {
	
	function onUpdateStroke():Void;
	
}