/* 
 * Generated by ASDT 
*/ 

/*
klasse:			DisplayUI
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		31.03.2005
zuletzt bearbeitet:	31.03.2005
durch			gj
status:			in bearbeitung
*/

class com.adgamewonderland.agw.kicker.DisplayUI extends MovieClip {
	
	private static var STRENGTH_FRAMES:Number = 12; // anzahl frames fuer animation schussstaerke anzeige
	
	private var myScore:Number;
	
	private var myStrength:Number;
	
	private var score_txt:TextField;
	
	private var strength_mc:MovieClip;
	
	public function DisplayUI()
	{
		// punktzahl
		myScore = 0;
		// schussstaerke
		myStrength = 0;
		// punktzahl ausrichten
		score_txt.autoSize = "right";
		// schussstaerke anzeige resetten
		strength_mc.gotoAndStop(1);
	}
	
	public function showScore(score:Number ):Void
	{
		// punktzahl
		myScore = score;
		// anzeigen
		score_txt.text = String(score);
	}
	
	public function showStrength(strength:Number ):Void
	{
		// schussstaerke
		myStrength = strength;
		// hoch / runter
		if (strength > 0) {
			// entsprechender frame in schussstaerke anzeige
			var frame:Number = Math.round(strength * STRENGTH_FRAMES / 100);
			// hinspringen
			strength_mc.gotoAndStop(frame);
		} else {
			// entsprechender frame in schussstaerke anzeige
			var frame:Number = STRENGTH_FRAMES + Math.round((1 - strength_mc._currentframe / STRENGTH_FRAMES) * (strength_mc._totalframes - STRENGTH_FRAMES));
			// hinspringen
			strength_mc.gotoAndPlay(frame);
		}
	}
}