/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.aldi.pipeman.beans.Pipe;

class com.adgamewonderland.aldi.pipeman.beans.Cell {
	
	private var id:Number;
	
	private var row:Number;
	
	private var column:Number;
	
	private var editable:Boolean;
	
	private var blocked:Boolean;
	
	private var pipe:Pipe;
	
	private var flow:Boolean;
	
	public function Cell() {
		this.id = 0;
		this.row = 0;
		this.column = 0;
		this.editable = true;
		this.blocked = false;
		this.pipe = null;
		this.flow = false;
	}
	
	public function hasPipe():Boolean
	{
		// mit pipe belegt oder nicht
		return (getPipe() instanceof Pipe);	
	}
	
	public function removePipe():Void
	{
		// pipe loeschen
		setPipe(null);
	}
	
	public function getId():Number {
		return id;
	}

	public function setId(id:Number):Void {
		this.id = id;
	}

	public function getRow():Number {
		return row;
	}

	public function setRow(row:Number):Void {
		this.row = row;
	}

	public function getEditable():Boolean {
		return editable;
	}

	public function setEditable(editable:Boolean):Void {
		this.editable = editable;
	}

	public function getColumn():Number {
		return column;
	}

	public function setColumn(column:Number):Void {
		this.column = column;
	}

	public function getPipe():Pipe {
		return pipe;
	}

	public function setPipe(pipe:Pipe):Void {
		this.pipe = pipe;
	}

	public function getBlocked():Boolean {
		return blocked;
	}

	public function setBlocked(blocked:Boolean):Void {
		this.blocked = blocked;
	}

	public function getFlow():Boolean {
		return flow;
	}

	public function setFlow(flow:Boolean):Void {
		this.flow = flow;
	}
	
	public function toString():String {
		return "Cell: id=" + getId() + ", row=" + getRow() + ", column=" + getColumn() + ", pipe=" + getPipe();
	}

}