/* 
 * Generated by ASDT 
*/ 

class com.adgamewonderland.aldi.chickenbowling.ui.DisplayUI {
	
	private var score_txt:TextField;
	
	public function DisplayUI() {
		// textfelder linksbuendig
		score_txt.autoSize = "left";
	}
	
	public function showScore(score:Number ):Void
	{
		// anzeigen
		score_txt.text = String(score);
	}
}