/* 
 * Generated by ASDT 
*/ 

/*
klasse:			UserTrackStatistic
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		15.06.2005
zuletzt bearbeitet:	15.06.2005
durch			gj
status:			in bearbeitung
*/

class com.adgamewonderland.blaupunkt.dtmracing.statistic.UserTrackStatistic {
	
    private var tid:Number;

    private var racetime:Number;
    
    public function UserTrackStatistic(tid:Number, racetime:Number )
    {
    	// tid
    	this.tid = tid;
    	// racetime
    	this.racetime = racetime;
    }

    public function getTid():Number
    {
        return tid;
    }

    public function setTid(num:Number )
    {
        tid = num;
    }

    public function getRacetime():Number
    {
        return racetime;
    }

    public function setRacetime(num:Number )
    {
        racetime = num;
    }
}