/* 
 * Generated by ASDT 
*/ 

class com.adgamewonderland.agw.util.Fader {
	
	public static function fade(target:MovieClip, alphastart:Number, alphaend:Number, duration:Number, steps:Number ):Void
	{
		// dauer interval
		var timediff:Number = Math.round(duration / steps);
		// differenz alpha
		var alphadiff:Number = Math.round((alphastart - alphaend) / steps);
		// interval
		var interval:Number;
		// stepcounter
		var stepcounter:Number = 0;
		// fade funktion
		var doFade:Function = function():Void {
			// alpha setzen
			target._alpha = alphastart - stepcounter * alphadiff;
			// steps zaehlen und ggf. beenden
			if (stepcounter++ == steps) clearInterval(interval);
		};
		// faden
		interval = setInterval(doFade, timediff);
	}
}