/* 
 * Generated by ASDT 
*/ 

/*
klasse:			Playable
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		01.04.2005
zuletzt bearbeitet:	01.04.2005
durch			gj
status:			in bearbeitung
*/

interface com.adgamewonderland.agw.util.Playable {

	function showSplash():Void;
	
	function showInstructions(bool:Boolean):Void;
	
	function showHighscore(editable:Boolean, score:Number ):Void;
	
	function startGame():Void;
	
	function restartGame():Void;
	
	function stopGame():Void;
	
	function toggleSound(bool:Boolean):Void;
	
}