/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.eplus.ayyildiz.*;

class com.adgamewonderland.eplus.ayyildiz.ButtonHomeUI extends ButtonMainUI {
	
	public function onRelease():Void
	{
		// seite aufrufen
		myNavigation.openPage("0,0");
	}
	
}