/* 
 * Generated by ASDT 
*/ 

class com.adgamewonderland.eplus.ayyildiz.LanguageUI extends MovieClip {
	
	private static var SCRIPT:String = "javascript:setLanguageFlash";
	
	public static var LANG_TR:Number = 0;
	
	public static var LANG_DE:Number = 1;
	
	private var bu_tr:MovieClip;
	
	private var bu_de:MovieClip;
	
	public function LanguageUI()
	{
		// button tuerkisch
		bu_tr.onRelease = function() {
			this._parent.changeLanguage(LanguageUI.LANG_TR);
		};
		// button deutsch
		bu_de.onRelease = function() {
			this._parent.changeLanguage(LanguageUI.LANG_DE);
		};
	}
	
	private function changeLanguage(num:Number ):Void
	{
		// url
		var url:String = SCRIPT + "(" + num + ");";
		// aufrufen
		this.getURL(url, "");
	}
	
}