/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.agw.util.*;

import com.adgamewonderland.eplus.ayyildiz.*;

class com.adgamewonderland.eplus.ayyildiz.NaviMainUI extends MovieClip {
	
	private static var PAUSE:Number = 250;
	
	public static var ANIMATION_IN:Number = 1;
	
	public static var ANIMATION_OUT:Number = 2;
	
	public static var ANIMATION_NONE:Number = 3;
	
	private var myId:Number; // id steht auf zeitleiste
	
	private var myNavigation:NavigationUI;
	
	private var myInterval:Number;
	
	private var button_mc:ButtonMainUI;
	
	public function NaviMainUI()
	{
		// navigation
		myNavigation = NavigationUI(_parent);
	}
	
	public function set id(num:Number ):Void
	{
		// id steht auf zeitleiste
		myId = num;
		// registrieren
		myNavigation.registerNaviMain(this, id);
	}
	
	public function get id():Number
	{
		// id steht auf zeitleiste
		return myId;
	}
	
	public function showAnimation(dir:Number ):Void
	{
		// frame
		var frame:String = (dir == ANIMATION_IN ? "frIn" : "frOut");
		// abspielen
		if (dir == ANIMATION_IN || dir == ANIMATION_OUT) {
			gotoAndPlay(frame);
		} else {
			gotoAndStop(frame);
		}
	}
	
	public function resetNavi():Void
	{
		// nach pause zum anfang
		myInterval = setInterval(this, "init", PAUSE);
	}
	
	public function init():Void
	{
		// interval loeschen
		clearInterval(myInterval);
		// zum anfang
 		this.gotoAndStop(1);
	}
	
	public function closeNavi(idsub:Number ):Void
	{
		// id aus haupt- und subnavigation
		var page:String = id + NavigationUI.DELIMITER + idsub;
		// seite aufrufen
		myNavigation.openPage(page);
	}
	
	
	
}