/*
 * Generated by ASDT
*/

import com.adgamewonderland.eplus.ayyildiz.*;

class com.adgamewonderland.eplus.ayyildiz.Pages {

	private static var NUMNAVIMAIN:Number = 8;

	private var myPages:Array = new Array();

	public function Pages()
	{
		// arrays fuer seiten je hauptnavigationspunkt
		for (var i:Number = 0; i <= NUMNAVIMAIN; i++) {
			myPages[i] = new Array();
		}
		// liste aller ueber die navigation erreichbaren seiten
		myPages[0][0] = "index.jsp";

		myPages[1][1] = "101_ueber_ayyildiz.jsp";
		myPages[1][2] = "102_jobs.jsp";
		myPages[1][4] = "104_presse.jsp";
		myPages[1][5] = "105_elele.jsp";
		myPages[1][3] = "502_downloads.jsp";
		myPages[1][6] = "503_1cent.jsp";

		myPages[2][1] = "201_tarife.jsp";
		myPages[2][2] = "201_tarif_sohbet.jsp";
		myPages[2][3] = "201_tarif_cepli.jsp";
		myPages[2][4] = "201_tarif_prepaid.jsp";
		myPages[2][5] = "201_tarifrechner_sohbet.jsp";
		myPages[2][6] = "201_tarif_ayde.jsp";
		myPages[2][7] = "201_tarif_cepradio.jsp";
		myPages[2][9] = "201_tarif_ligtv.jsp";
		myPages[2][10] = "201_tarif_daten_roaming_limit.jsp";
		myPages[2][11] = "201_mobiles_internet.jsp";

		myPages[3][1] = "301_vorteile.jsp";
		myPages[3][2] = "ShopStart";

		myPages[4][1] = "403_kundenservice.jsp";
		myPages[4][2] = "401_aufladen.jsp";
		myPages[4][3] = "402_faq.jsp";
		myPages[4][4] = "Shopfinder";
		myPages[4][5] = "504_sipsak.jsp";
		
//		myPages[5][1] = "404_partnerprogramm.jsp";
		
		myPages[6][1] = "601_handy_uebersicht.jsp";
		myPages[6][2] = "601_alle_handys.jsp";

//		myPages[7][1] = "javascript:puAyworld();";

		myPages[8][1] = "701_werben.jsp";
		myPages[8][2] = "701_freundschaftswerbung.jsp";
		myPages[8][3] = "701_e-seller.jsp";
		myPages[8][4] = "404_partnerprogramm.jsp";
	}

	public function setPageOrder(page:String ):Void
	{
		// vollständiger pfad zur bestellung
		myPages[3][2] = page;
	}

	public function getPage(id:String ):String
	{
		// aufteilen
		var ids:Array = id.split(NavigationUI.DELIMITER);
		trace(ids);
		// zurueck geben
		return (myPages[ids[0]][ids[1]]);
	}
}