/* 
 * Generated by ASDT 
*/ 

/*
klasse:			Award
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			blaupunkt
erstellung: 		23.06.2005
zuletzt bearbeitet:	23.06.2005
durch			gj
status:			in bearbeitung
*/

import com.adgamewonderland.blaupunkt.dtmracing.challenge.*;

class com.adgamewonderland.blaupunkt.dtmracing.challenge.Award {

    private var cid:Number;

    private var mailid:String;

    private var didchallenger:Number;

    private var didopponent:Number;

    private var status:Number;

    private var tid:Number;
    
    private var challengerDetail:ChallengeDetail;
    
    private var opponentDetail:ChallengeDetail;
    
    public function Award() {
    	// eindeutige id
    	this.cid = null;
    	// id in email
    	this.mailid = "";
    	// referenz auf challenger
    	this.didchallenger = null;
    	// referenz auf opponent
    	this.didopponent = null;
    	// status
    	this.status = 0;
    	// rennstrecke
    	this.tid = 0;
    	// details zum challenger
    	this.challengerDetail = challengerDetail;
    	// details zum opponent
    	this.opponentDetail = opponentDetail;
    }
    
    public function setCid(num:Number ):Void
    {
    	// cid
    	cid = num;
    }
    
    public function getCid():Number
    {
    	// cid
    	return cid;
    }
    
    public function setMailid(str:String ):Void
    {
    	// mailid
    	mailid = str;
    }
    
    public function getMailid():String
    {
    	// mailid
    	return mailid;
    }
    
    public function setDidchallenger(num:Number ):Void
    {
    	// didchallenger
    	didchallenger = num;
    }
    
    public function getDidchallenger():Number
    {
    	// didchallenger
    	return didchallenger;
    }
    
    public function setDidopponent(num:Number ):Void
    {
    	// didopponent
    	didopponent = num;
    }
    
    public function getDidopponent():Number
    {
    	// didopponent
    	return didopponent;
    }
    
    public function setStatus(num:Number ):Void
    {
    	// status
    	status = num;
    }
    
    public function getStatus():Number
    {
    	// status
    	return status;
    }
    
    public function setTid(num:Number ):Void
    {
    	// rennstrecke
    	tid = num;
    }
    
    public function getTid():Number
    {
    	// rennstrecke
    	return tid;
    }
    
    public function setChallengerDetail(details:ChallengeDetail ):Void
    {
    	// details zum challenger
    	challengerDetail = details;
    }
    
    public function getChallengerDetail():ChallengeDetail
    {
    	// details zum opponent
    	return challengerDetail;
    }
    
    public function setOpponentDetail(details:ChallengeDetail ):Void
    {
    	// details zum opponent
    	opponentDetail = details;
    }
    
    public function getOpponentDetail():ChallengeDetail
    {
    	// details zum opponent
    	return opponentDetail;
    }
}