/* 
 * Generated by ASDT 
*/ 

/*
klasse:			ChallengeLapresult
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		19.06.2005
zuletzt bearbeitet:	19.06.2005
durch			gj
status:			in bearbeitung
*/

class com.adgamewonderland.blaupunkt.dtmracing.challenge.ChallengeLapresult {

    private var lap:Number;

    private var laptime:Number;
    
    public function ChallengeLapresult(lap:Number, laptime:Number )
    {
    	// runde
    	this.lap = lap;
    	// rundenzeit
    	this.laptime = laptime;
    }
    
    public function setLap(num:Number ):Void
    {
    	// runde
    	lap = num;
    }
    
    public function getLap():Number
    {
    	// runde
    	return lap;
    }
    
    public function setLaptime(num:Number ):Void
    {
    	// rundenzeit
    	laptime = num;
    }
    
    public function getLaptime():Number
    {
    	// rundenzeit
    	return laptime;
    }
}