/* 
 * Generated by ASDT 
*/ 

/*
klasse:			Track
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			blaupunkt
erstellung: 		16.06.2005
zuletzt bearbeitet:	16.06.2005
durch			gj
status:			in bearbeitung
*/

class com.adgamewonderland.blaupunkt.dtmracing.challenge.Track {
	
    private var tid:Number;

    private var name:String;

    private var country:String;

    private var validfrom:Date;

    private var validto:Date;

    private var active:Number;
    
    public function Track() {
    	
    }

    public function getTid():Number
    {
        return tid;
    }

    public function setTid(num:Number )
    {
        tid = num;
    }

    public function getName():String
    {
        return name;
    }

    public function setName(str:String )
    {
        name = str;
    }

    public function getCountry():String
    {
        return country;
    }

    public function setCountry(str:String  )
    {
        country = str;
    }

    public function getValidfrom():Date
    {
        return validfrom;
    }

    public function setValidfrom(date:Date )
    {
        validfrom = date;
    }

    public function getValidto():Date
    {
        return validto;
    }

    public function setValidto(date:Date )
    {
        validto = date;
    }

    public function getActive():Number
    {
        return active;
    }

    public function setActive(num:Number )
    {
        active = num;
    }
    
    
}