/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.sskddorf.remote.*;

class com.adgamewonderland.sskddorf.remote.DisplayUI extends MovieClip {
	
	private var myInterval:Number;
	
	private var myDescription:String;
	
	private var description_txt:TextField;
	
	private var description_mc:MovieClip;
	
	private var light_mc:MovieClip;
	
	public function DisplayUI()
	{
		// aktuelle beschreibung
		myDescription = "";
		// interval fuer licht
		myInterval = null;

	}
	
	public function showDescription(description:String ):Void
	{
		// beschreibung anzeigen
//		description_txt.text = description;
		// testen, ob beschreibung geaendert
		if (description != myDescription) {
			// beschreibung anzeigen
			description_mc.txt_mc.description_txt.text = String(description);
			// ein- / ausblenden
			description_mc.gotoAndPlay(description == "" ? "frOff" : "frOn");
			// aktuelle beschreibung
			myDescription = description;
		}
	}
	
	public function showLight(onoff:Boolean ):Void
	{
		// ein- / ausschalten
		switch (onoff) {
			// ein
			case true :
				// licht an
				if (myInterval == null) light_mc.gotoAndPlay("frOn");
				// interval loeschen
				clearInterval(myInterval);
				// nullen
				myInterval = null;
				
				break;	
			// aus
			case false :
				// nach pause ausschalten
				myInterval = setInterval(this, "stopLight", RemoteUI(_parent).getConfig().displaytime);
				
				break;	
		}
	}
	
	private function stopLight():Void
	{
		// interval loeschen
		clearInterval(myInterval);
		// nullen
		myInterval = null;
		// ausschalten
		light_mc.gotoAndPlay("frOff");
		// beschreibung loeschen
		showDescription("");
	}
}