/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.sskddorf.remote.*;

class com.adgamewonderland.sskddorf.remote.ItemUI extends MovieClip {
	
	private var _myId:Number;
	
	private var myItem:Item;
	
	private var id_txt:TextField;
	
	private var label_txt:TextField;
	
	public function ItemUI()
	{
		// anzuzeigendes item
		myItem = null;
		// bei fernbedienung registrieren
		RemoteUI(_parent).registerItemUI(_myId, this);
	}
	
	public function init(item:Item ):Void
	{
		// anzuzeigendes item
		myItem = item;
		// text anzeigen
		showText();
	}
	
	public function onRollOver():Void
	{
		// display
		var display:DisplayUI = RemoteUI(_parent).getDisplay();
		// description anzeigen
		display.showDescription(myItem.description);
		// licht einschalten
		display.showLight(true);
	}
	
	public function onRelease():Void
	{
		// link oeffnen
		RemoteUI(_parent).openLink(myItem.path);
	}
	
	public function onRollOut():Void
	{
		// display
		var display:DisplayUI = RemoteUI(_parent).getDisplay();
		// licht ausschalten
		display.showLight(false);
	}
	
	private function showText():Void
	{
		// id anzeigen
		id_txt.text = String(myItem.id);
		// label anzeigen
		label_txt.text = myItem.label;
	}
	
}