/* 
 * Generated by ASDT 
*/ 
 
import com.adgamewonderland.digitalbanal.elfmeterduell.beans.*;

class com.adgamewonderland.digitalbanal.elfmeterduell.beans.GameImpl extends Game {
	
	public function GameImpl() {
		super.constructor.apply(super, arguments);
	}
	
	public function addDetail(mode:Number, detail:GameDetail ):Void
	{
		// details speichern
		getGameDetails()[mode] = detail;
	}
	
	public function getDetail(mode:Number ):GameDetail
	{
		// zur sicherheit sortieren
		getGameDetails().sortOn("mode");
		// details zurueck geben
		return getGameDetails()[mode];
	}
}