/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.digitalbanal.elfmeterduell.beans.*;

interface com.adgamewonderland.digitalbanal.elfmeterduell.beans.IUserListener {
	
	public function onUserLogin(user:User ):Void;
	
	public function onUserLogout(user:User ):Void;
	
	public function onUserUpdate(user:User ):Void;
}