/* 
 * Generated by ASDT 
*/ 

class com.adgamewonderland.digitalbanal.elfmeterduell.ui.ChallengedUI extends MovieClip {
	
	private var voting_btn:Button;
	
	public function ChallengedUI() {
	}
	
	public function init():Void
	{
		// button zum voting zwergenmannschaft
		voting_btn.onRelease = function():Void {
			getURL("http://www.itelligence.de/", "_blank");
		};
	}
}