/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.agw.*;

import com.adgamewonderland.digitalbanal.elfmeterduell.beans.*;

import com.adgamewonderland.digitalbanal.elfmeterduell.connectors.*;

import com.adgamewonderland.digitalbanal.elfmeterduell.ui.InputUI;

import com.adgamewonderland.digitalbanal.elfmeterduell.ui.NoticeUI;

class com.adgamewonderland.digitalbanal.elfmeterduell.ui.ChallengeUI extends InputUI {
	
	private var email_txt:TextField;
	
	private var send_btn:Button;
	
	public function ChallengeUI() {
	}
	
	public function init():Void
	{
		// notice anzeigen
		NoticeUI.getNoticeUI().showNotice(NoticeUI.NOTICE_CHALLENGE, true);
		// herausforderung senden
		send_btn.onRelease = function():Void {
			this._parent.sendChallenge();
		};
	}
	
	public function setOpponent(email:String ):Void
	{
		// anzeigen
		email_txt.text = email;	
	}
	
	public function sendChallenge():Void
	{
		// fehler ausblenden
		showErrors([]);
		// validieren, ob 1. korrekte email adresse
		var errors:Array = (new Formprocessor()).checkForm([3, "email", email_txt.text]);
		// testen, ob fehler gefunden
		if (errors.length != 0) {
			// fehler anzeigen
			showErrors(errors);
			// abbrechen
			return;
		}
		// meldung anzeigen
//		trace("Daten werden gesendet!");
		// notice ausblenden
		NoticeUI.getNoticeUI().showNotice(NoticeUI.NOTICE_CHALLENGE, false);
		// button ausblenden
		send_btn._visible = false;
		// herausforderung senden lassen
		GameController.getInstance().startChallenge(email_txt.text);
	}
}