/* 
 * Generated by ASDT 
*/ 

class com.adgamewonderland.digitalbanal.elfmeterduell.ui.CounterUI extends MovieClip {
	
	private var counter1_txt:TextField;
	
	private var counter2_txt:TextField;
	
	public function CounterUI() {
		// linksbuendig
		counter1_txt.autoSize = counter2_txt.autoSize = "left";
		// anzeigen
		counter1_txt.text = counter2_txt.text = String(_parent.getCount());
	}
}