/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.digitalbanal.elfmeterduell.ui.*;

class com.adgamewonderland.digitalbanal.elfmeterduell.ui.DisplayaniUI extends MovieClip {
	
	public function DisplayaniUI() {
		
	}
	
	public function showDisplayani(inout:Boolean, pause:Number ):Void
	{
		// frame
		var frame:String = (inout ? "frIn" : "frOut");
		// nach pause abspielen
		var interval:Number;
		// funktion
		var doStart:Function = function(mc:MovieClip ):Void {
			// abspielen
			mc.gotoAndPlay(frame);
			// interval loeschen
			clearInterval(interval);
		};
		// umschalten
		interval = setInterval(doStart, pause, this);
	}
	
}