/* 
 * Generated by ASDT 
*/ 

class com.adgamewonderland.digitalbanal.elfmeterduell.ui.InputUI extends MovieClip {
	
	private var errormcs:Array;
	
	public function InputUI() {
		// auf der buehne angezeigte fehlerpfeile
		errormcs = new Array();
	}
	
	private function showErrors(errors:Array ):Void
	{
		// fehlerpfeile loschen
		if (errors.length == 0) {
			// schleife ueber fehlerpfeile
			for (var j : String in errormcs) {
				// aktueller fehlerpfeil
				errormcs[j].removeMovieClip();
			}
			// array leeren
			this.errormcs.splice(0);
		
		// fehlerpfeile anzeigen	
		} else {
			// schleife ueber fehler
			for (var i:String in errors) {
				// fehler (name der variable)
				var error:String = errors[i];
				// textfeld oder movieclip
				var target:Object;
				if (this[error + "_txt"] instanceof TextField) {
					target = this[error + "_txt"];
				} else if (this[error + "_mc"] instanceof MovieClip) {
					target = this[error + "_mc"];
				}
				// testen, ob gefunden
				if (target == undefined) continue;
				// rechte mittlere ecke
				var xpos:Number = target._x + target._width;
				var ypos:Number = target._y + target._height / 2;
				// constructor
				var constructor:Object = {_x : xpos, _y : ypos};
				// neuer fehlerpfeil
				var mc:MovieClip = this.attachMovie("ErrorUI", "error" + error + "_mc", getNextHighestDepth(), constructor);
				// speichenr
				this.errormcs.push(mc);
			}
		}
	}
	
	
}