/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.agw.util.i18n.*;

class com.adgamewonderland.digitalbanal.elfmeterduell.ui.InstructionsUI extends I18nUI {
	
	public function InstructionsUI() {
		
	}
}