/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.digitalbanal.elfmeterduell.ui.*;

class com.adgamewonderland.digitalbanal.elfmeterduell.ui.MoveButtonDefense extends MoveButton {
	
	public function MoveButtonDefense() {
		super();
	}
	
	public function onRollOver():Void
	{
		// keeper ausblenden
		SoccerUI.getSoccerUI().showKeeper(false);
	}
	
	public function onRollOut():Void
	{
		// keeper einblenden
		SoccerUI.getSoccerUI().showKeeper(true);
	}
	
	public function onReleaseOutside():Void
	{
		onRollOut();	
	}
}