/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.digitalbanal.elfmeterduell.ui.*;

import com.adgamewonderland.digitalbanal.elfmeterduell.beans.*;

class com.adgamewonderland.digitalbanal.elfmeterduell.ui.RegisteredUI extends MovieClip {
	
	private var nickname_txt:TextField;
	
	private var userdata_btn:Button;
	
	public function RegisteredUI() {
		// nickname linksbuendig
		nickname_txt.autoSize = "left";
	}
	
	public function init():Void
	{
		// nickname
		nickname_txt.text = GameController.getInstance().getUser().getNickname();
		// button userdata
		userdata_btn.onRelease = function():Void {
			CardUI.getCardUI().showUserdata();
		};
	}
}