/* 
 * Generated by ASDT 
*/ 
 
import mx.remoting.debug.NetDebug;
import mx.rpc.ResultEvent;
import mx.rpc.FaultEvent;

import com.adgamewonderland.agw.net.*;

import com.adgamewonderland.digitalbanal.elfmeterduell.beans.*;

import com.adgamewonderland.digitalbanal.elfmeterduell.connectors.*;

class com.adgamewonderland.digitalbanal.elfmeterduell.ui.StatisticsUI extends MovieClip {
	
	private var rank_txt:TextField;
	
	private var gameswon_txt:TextField;
	
	private var gameslost_txt:TextField;
	
	private var gamesdrawn_txt:TextField;
	
	private var goalsoffense_txt:TextField;
	
	private var goalsdefense_txt:TextField;
	
	private var score_txt:TextField;
	
	public function StatisticsUI() {
		// alle textfelder linksbuendig
		rank_txt.autoSize = "left";
		gameswon_txt.autoSize = "left";
		gameslost_txt.autoSize = "left";
		gamesdrawn_txt.autoSize = "left";
		goalsoffense_txt.autoSize = "left";
		goalsdefense_txt.autoSize = "left";
		score_txt.autoSize = "left";
		// statistics laden lassen
		ChallengeC.loadStatistics(GameController.getInstance().getUser().getUserID(), this, "onStatisticLoaded");
	}
	
	public function onStatisticLoaded(re:ResultEvent ):Void
	{
		// neue statistics
		var statistics:Statistics = Statistics(RemotingBeanCaster.getCastedInstance(new Statistics(), re.result));
		// alle werte anzeigen
		gameswon_txt.text = String(statistics.getGameswon());
		gameslost_txt.text = String(statistics.getGameslost());
		gamesdrawn_txt.text = String(statistics.getGamesdrawn());
		goalsoffense_txt.text = String(statistics.getGoalsoffense());
		goalsdefense_txt.text = String(statistics.getGoalsdefense());
		score_txt.text = String(statistics.getScore());
		rank_txt.text = String(statistics.getRank());
		// user intern updaten
		GameController.getInstance().getUser().setStatistics(statistics);
	}
}