/* 
 * Generated by ASDT 
*/ 

/*
klasse:			DrawingBoard
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		18.05.2005
zuletzt bearbeitet:	21.05.2005
durch			gj
status:			in bearbeitung
*/

import com.adgamewonderland.agw.math.*;

class com.adgamewonderland.agw.graph.DrawingBoard {
	
	private var myTarget:MovieClip;
	
	public function DrawingBoard(target:MovieClip )
	{
		// ziel, in das gezeichnet wird
		myTarget = target;
	}
	
	public function drawPolygon(polygon:Polygon, showcenter:Boolean ):Void
	{
		// naechste tiefe
		var depth:Number = myTarget.getNextHighestDepth();
		// neues movieclip zum zeichnen
		var mc:MovieClip = myTarget.createEmptyMovieClip(depth.toString(), depth);
		// raender des polygons
		var borders:Array = polygon.borders;
		// schwerpunkt des polygons
		var center:Point = polygon.center;
		// schleife ueber die raender
		for (var i:Number = 0; i < borders.length; i++) {
			// aktueller rand
			var b:Border = borders[i];
			// startpunkt
			var pstart:Point = b.getPoint("start");
			// zielpunkt
			var pend:Point = b.getPoint("end");
			// zum startpunkt
			mc.moveTo(pstart.x, pstart.y);
			// linie TODO: klassenbasiert und dynamisch
			mc.lineStyle(1, 0xFF00CC, 100);
			// zum zielpunkt
			mc.lineTo(pend.x, pend.y);
			// zum schwerpunkt
			if (showcenter) mc.lineTo(center.x, center.y);
		}
	}
	
	public function setStyle(thickness:Number , color:Number , alpha:Number ):Void
	{
		// TODO: linienstile in klassen bauen (z.b. LineStyle)	
	}
}