/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.aldi.ecard.beans.User;

class com.adgamewonderland.aldi.ecard.beans.Ecard {
	
	private var sender:User;
	
	private var receiver:User;
	
	private var message:String;
	
	private var layout:XML;
	
	public function Ecard() {
		this.sender = new User();
		this.receiver = new User();
		this.message = "";
		this.layout = new XML();
	}
	
	public function getMessage():String {
		return message;
	}

	public function setMessage(message:String):Void {
		this.message = message;
	}

	public function getSender():User {
		return sender;
	}

	public function setSender(sender:User):Void {
		this.sender = sender;
	}

	public function getLayout():XML {
		return layout;
	}

	public function setLayout(layout:XML):Void {
		this.layout = layout;
	}

	public function getReceiver():User {
		return receiver;
	}

	public function setReceiver(receiver:User):Void {
		this.receiver = receiver;
	}

}