/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.aldi.ecard.beans.Item;

class com.adgamewonderland.aldi.ecard.beans.ItemText extends Item {
	
	public static var TYPE:String = "text";
	
	public static var DEFAULT_COLOR:Number = 0x000000;
	
	public static var DEFAULT_FONT:String = "ALDI SUED Regular";
	
	public static var DEFAULT_TEXT:String = "Ihr Text";
	
	private var color:Number;
	
	private var font:String;
	
	private var text:String;
	
	public function ItemText() {
		super.constructor.apply(super, arguments);
		this.type = ItemText.TYPE;
		this.color = DEFAULT_COLOR;
		this.font = DEFAULT_FONT;
		this.text = DEFAULT_TEXT;
	}
	
	public function getAsXml():XML {
		// xml
		var item:XML = super.getAsXml.apply(super, arguments);
		// type
		item.firstChild.attributes["type"] = getType();
		// color
		item.firstChild.attributes["color"] = getColor();
		// font
		item.firstChild.attributes["font"] = getFont();
		// text
		item.firstChild.appendChild(item.createTextNode(getText()));
		
		// zurueck geben
		return item;
	}
	
	public function getColor():Number {
		return color;
	}

	public function setColor(color:Number):Void {
		this.color = color;
	}

	public function getFont():String {
		return font;
	}

	public function setFont(font:String):Void {
		this.font = font;
	}

	public function getText():String {
		return text;
	}

	public function setText(text:String):Void {
		if (text != undefined && text != "undefined") {
			this.text = text;
		} else {
			this.text = "";
		}
	}

}