/* 
 * Generated by ASDT 
*/ 

import de.kruesch.event.*;

import com.adgamewonderland.agw.util.i18n.*;

class com.adgamewonderland.agw.util.i18n.I18nController {
	
	private static var _instance:I18nController;
	
	private static var EVENT_LANGUAGECHANGED:String = "onLanguageChanged";
	
	private var _event:EventBroadcaster;
	
	private var language:Language;
	
	public static function getInstance():I18nController {
		if (_instance == null)
			_instance = new I18nController();
		return _instance;
	}
	
	public function addListener(l ):Void
	{
		_event.addListener(l);
	}
	
	public function removeListener(l ):Void
	{
		_event.removeListener(l);
	}

	public function getLanguage():Language {
		return language;
	}

	public function setLanguage(language:Language ):Void {
		this.language = language;
		// listener informieren
		_event.send(EVENT_LANGUAGECHANGED, language);
	}
	
	private function I18nController() {
		language = new Language(Language.GERMAN);
		_event = new EventBroadcaster();
	}

}