/* 
 * Generated by ASDT 
*/ 

class com.adgamewonderland.agw.util.i18n.Language {
	
	public static var GERMAN:String = "DE";
	
	public static var ENGLISH:String = "EN";
	
	private var language:String;
	
	public function Language(language:String ) {
		this.language = language;
	}
	
	public function getLanguage():String {
		return language;
	}

	public function setLanguage(language:String):Void {
		this.language = language;
	}

}