/* 
 * Generated by ASDT 
*/ 

/*
klasse:			DirectionUI
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		14.06.2005
zuletzt bearbeitet:	14.06.2005
durch			gj
status:			in bearbeitung
*/

import com.adgamewonderland.agw.racing.track.*;

class com.adgamewonderland.agw.racing.vehicle.DirectionUI extends MovieClip {
	
	private var arrow_left_mc:MovieClip;
	
	private var arrow_right_mc:MovieClip;
	
	public function DirectionUI()
	{
		// pfeil nach links
		arrow_left_mc._visible = false;
		// pfeil nach rechts
		arrow_right_mc._visible = false;
	}
	
	public function showDirection(direction:Number ):Void
	{
		// pfeil nach links
		arrow_left_mc._visible = (direction == Track.DIRECTION_LEFT);
		// pfeil nach rechts
		arrow_right_mc._visible = (direction == Track.DIRECTION_RIGHT);
	}
	
}