/* 
 * Generated by ASDT 
*/ 

/*
klasse:			WarningUI
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		14.06.2005
zuletzt bearbeitet:	14.06.2005
durch			gj
status:			in bearbeitung
*/

class com.adgamewonderland.agw.racing.vehicle.WarningUI extends MovieClip {
	
	public static var WARNING_ONTRACK:Number = 1;
	
	public static var WARNING_INDIRECTION:Number = 2;
	
	private var ontrack_mc:MovieClip;
	
	private var indirection_mc:MovieClip;
	
	public function WarningUI()
	{
		// anzeige, ob auf der strasse
		ontrack_mc._visible = false;
		// anzeige, ob in richtiger richtung
		indirection_mc._visible = false;
	}
	
	public function showWarning(mode:Number, visible:Boolean ):Void
	{
		// je nach modus
		switch (mode) {
			// auf der strasse
			case WARNING_ONTRACK :
				// anzeige, ob auf der strasse
				ontrack_mc._visible = visible;
			
				break;
			// in richtiger richtung
			case WARNING_INDIRECTION :
				// anzeige, ob in richtiger richtung
				indirection_mc._visible = visible;
			
				break;
		}
	}
}