/* 
 * Generated by ASDT 
*/ 

import mx.remoting.PendingCall;
import mx.remoting.Service;
import mx.rpc.RelayResponder;

import com.adgamewonderland.aldi.ecard.beans.Ecard;

class com.adgamewonderland.aldi.ecard.connectors.EcardConnector {
	
	private static var myGatewayURL:String = "http://plasticbox/flashservices/gateway.php";
	
	private static var myRemoteObject:String = "com.adgamewonderland.aldi.ecard.connectors.EcardConnector";
	
	private static var myService:Service;	
	
	//ecard speichern	
	public static function saveEcard(ecard:Ecard, caller:Object, callback:String ):Void
	{
		// senden
		var pc:PendingCall = getService().saveEcard(ecard);
		// rueckgabe von rmi auswerten
		pc.responder = new RelayResponder(caller, callback, "onConnectorFault");
	}
		
	//ecard laden	
	public static function getEcard(id:Number, cryptid:String, caller:Object, callback:String ):Void
	{
		// senden
		var pc:PendingCall = getService().getEcard(id, cryptid);
		// rueckgabe von rmi auswerten
		pc.responder = new RelayResponder(caller, callback, "onConnectorFault");
	}
	
	private static function getService():Service
	{
		// testen, ob service schon instantiiert
		if (myService instanceof Service == false) {
			// debugger
//			NetDebug.initialize();
			// offline / online
			if (_url.indexOf("http://") == -1) {
				// remoting service mit url
				myService = new Service(myGatewayURL, null, myRemoteObject, null, null);
			} else {
				// remoting service ohne url
				myService = new Service("", null, myRemoteObject, null, null);
			}
		}
		// zurueck geben
		return myService;
	}
}