/* 
 * Generated by ASDT 
*/ 

import de.kruesch.event.*;

class com.adgamewonderland.sskddorf.mischpult.ui.CheckboxUI extends com.adgamewonderland.agw.util.CheckboxUI {
	
	private var _id:Number;
	
	private var _event:EventBroadcaster;
	
	public function CheckboxUI() {
		super();
		// event handling
		this._event = new EventBroadcaster();
		// aenderungen ueberwachen
		this.watch("myStatus", onStatusChanged, null);
	}
	
	public function addListener(l ):Void
	{
		_event.addListener(l);
	}
	
	public function removeListener(l ):Void
	{
		_event.removeListener(l);
	}
	
	public function onStatusChanged(prop:String, oldval:Boolean, newval:Boolean ):Boolean
	{
		// listener informieren
		_event.send("onCheckboxChecked", this._id, newval);
		// neuer status
		return newval;
	}
}