/* 
 * Generated by ASDT 
*/ 

/*
klasse:			Movable
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		06.03.2005
zuletzt bearbeitet:	31.03.2005
durch			gj
status:			final
*/

interface com.adgamewonderland.agw.physics.Movable {
	
	function setPosition(xpos:Number, ypos:Number ):Void;
	
	function onMove():Void;
	
	function onStopMove():Void;
}