/* 
 * Generated by ASDT 
*/ 

/*
interface:			Strokable
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		28.02.2005
zuletzt bearbeitet:	31.03.2005
durch			gj
status:			final
*/

interface com.adgamewonderland.agw.physics.Strokable {
	
	function onUpdateStroke():Void;
	
}