/* 
 * Generated by ASDT 
*/ 

/*
klasse:			Algebra
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		31.03.2005
zuletzt bearbeitet:	31.03.2005
durch			gj
status:			in bearbeitung
*/

class com.adgamewonderland.agw.math.Algebra {
	
	private static var _instance:Algebra;
	
	public static function getInstance():Algebra {
		if (_instance == null)
			_instance = new Algebra();
		return _instance;
	}
	
	public function getValueParabola(x:Number, a:Number, b:Number ):Number
	{
		// parabel wert (y = a * x² + b)
		return (a * x * x + b);
	}
	
	public function getValueLine(x:Number, a:Number, b:Number ):Number
	{
		// gerade wert (y = a * x + b)
		return (a * x + b);
	}
	
	private function Algebra() {
		
	}
}