/* 
 * Generated by ASDT 
*/ 

/*
klasse:			Border
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		18.05.2005
zuletzt bearbeitet:	21.05.2005
durch			gj
status:			in bearbeitung
*/

import com.adgamewonderland.agw.math.*;

class com.adgamewonderland.agw.math.Border {
	
	private var myPoints:Object;
	
	public function Border(point1:Point, point2:Point )
	{
		// die beiden punkte, die den rand umreissen
		myPoints = {start : point1, end : point2};
	}
	
	public function getPoint(mode:String ):Point
	{
		// entsprechender punkt
		return myPoints[mode];	
	}
}