/* 
 * Generated by ASDT 
*/ 

/*
klasse:			MiniTrackUI
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		07.06.2005
zuletzt bearbeitet:	28.06.2005
durch			gj
status:			in bearbeitung
*/

import com.adgamewonderland.agw.racing.race.*;

import com.adgamewonderland.agw.racing.vehicle.*;

class com.adgamewonderland.agw.racing.track.MiniTrackUI extends MovieClip {
	
	private var SCALE:Number = 4.5 / 2; // massstab in %
	
	private var XSHIFT:Array = new Array(-14, -14, -23, -20, -26, -22, -21, -20, -21, -23, -10);
	
	private var YSHIFT:Array = new Array(1, -15, -12, -7, -1, 2, -8, -21, 9, -7, -10);
	
	private var myTid:Number;
	
	private var myMiniVehicles:Array;
	
	private var vehicles_mc:MovieClip;
	
	public function MiniTrackUI()
	{
		// beim racecontroller anmelden
		RaceController.getInstance().minitrackui = this;
		// id der angezeigten Strecke
		myTid = 0;
		// movieclips, die die position der fahrzeuge angezeigen
		myMiniVehicles = [];
	}
	
	public function showTrack(tid:Number ):Void
	{
		// id der angezeigten Strecke
		myTid = tid;
		// hinspringen
		gotoAndStop(tid + 1);
	}
	
	public function showVehicle(vobj:Vehicle ):Void
	{
		// mini fahrzeug
		var minivehicle:MovieClip;
		// testen, ob noch nicht bekannt
		if (myMiniVehicles[vobj.id] == undefined) {
			// speichern
			minivehicle = addMiniVehicle(vobj);
		} else {
			// gespeichertes nehmen
			minivehicle = myMiniVehicles[vobj.id];
		}
		// positionieren
		minivehicle._x = vobj.position.x / 100 * SCALE + XSHIFT[myTid - 1];
		minivehicle._y = vobj.position.y / 100 * SCALE + YSHIFT[myTid - 1];
	}
	
	private function addMiniVehicle(vobj:Vehicle ):MovieClip
	{
		// attachen
		var minivehicle:MovieClip = vehicles_mc.attachMovie("minivehicle", "minivehicle" + vobj.id + "_mc", vehicles_mc.getNextHighestDepth(), {_myFrame : vobj.type + 1});
		// speichern
		myMiniVehicles[vobj.id] = minivehicle;
		// zurueck geben
		return minivehicle;
	}
}