/*
 * Generated by ASDT
*/

import mx.remoting.Service;
import mx.remoting.PendingCall;
// import mx.remoting.debug.NetDebug;
import mx.rpc.RelayResponder;
import mx.rpc.FaultEvent;
import mx.rpc.ResultEvent;

class com.adgamewonderland.brockhaus.mahjong.connectors.ReportingConnector {

	private static var myGatewayURL:String = "http://webbox/flashservices/gateway.php";

	private static var myRemoteObject:String = "com.adgamewonderland.meyers.mahjong.connectors.ReportingConnector";

	private static var myService:Service;

	// reporting speichern
	public static function putReporting(gameid:Number, trackid:Number, time:Number, phase:String, caller:Object, callback:String ):Void
	{
		// senden
		var pc:PendingCall = getService().putReporting(gameid, trackid, time, phase);
		// rueckgabe von rmi auswerten
		pc.responder = new RelayResponder(caller, callback, "onConnectorFault");
	}

	private static function getService():Service
	{
		// testen, ob service schon instantiiert
		if (myService instanceof Service == false) {
			// debugger
// 			NetDebug.initialize();
			// offline / online
			if (_url.indexOf("http://") == -1) {
				// remoting service mit url
				myService = new Service(myGatewayURL, null, myRemoteObject, null, null);
			} else {
				// remoting service ohne url
				myService = new Service("", null, myRemoteObject, null, null);
			}
		}
		// zurueck geben
		return myService;
	}
}