/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.aldi.sudoku.beans.Content;

class com.adgamewonderland.aldi.sudoku.beans.Field {
	
	private var id:Number;
	
	private var solution:Content;
	
	private var content:Content;
	
	private var guesses:Array;
	
	private var editable:Boolean;
	
	private var solved:Boolean;
	
	public function Field() {
		this.id = null;
		this.solution = null;
		this.content = null;
		this.guesses = new Array();
		this.editable = false;
		this.solved = false;
	}
	
	public function getId():Number {
		return id;
	}

	public function setId(id:Number):Void {
		this.id = id;
	}

	public function getSolution():Content {
		return solution;
	}

	public function setSolution(solution:Content):Void {
		this.solution = solution;
	}

	public function getGuesses():Array {
		return guesses;
	}

	public function setGuesses(guesses:Array):Void {
		this.guesses = guesses;
	}

	public function getEditable():Boolean {
		return editable;
	}

	public function setEditable(editable:Boolean):Void {
		this.editable = editable;
	}

	public function getContent():Content {
		return content;
	}

	public function setContent(content:Content):Void {
		this.content = content;
	}

	public function getSolved():Boolean {
		return solved;
	}

	public function setSolved(solved:Boolean):Void {
		this.solved = solved;
	}

}