/* 
 * Generated by ASDT 
*/ 

/*
klasse:			TrackPiece
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			agw
erstellung: 		19.05.2005
zuletzt bearbeitet:	07.06.2005
durch			gj
status:			in bearbeitung
*/

import com.adgamewonderland.agw.math.*;

class com.adgamewonderland.agw.racing.track.TrackPiece {
	
	public static var TYPE_ROAD:Number = 1;
	
	public static var TYPE_OFFROAD:Number = 2;

	private var myId:Number;
	
	private var myType:Number;
	
	private var myPolygon:Polygon;
	
	private var myConnection:Vector;
	
	public function TrackPiece(id:Number, type:Number )
	{
		// eindeutige id
		myId = id;
		// typ des streckenteils (road darf befahren werden, offroad nicht)
		myType = type;
		// polygon des streckenstuecks
		myPolygon = null;
		// verbindungsvektor zum naechsten streckenteil
		myConnection = null;
	}
	
	public function get id():Number
	{
		// eindeutige id
		return myId;
	}
	
	public function get type():Number
	{
		// typ des streckenteils (road darf befahren werden, offroad nicht)
		return myType;
	}
	
	public function set polygon(pobj:Polygon ):Void
	{
		// polygon des streckenstuecks
		myPolygon = pobj;
	}
	
	public function get connection():Vector
	{
		// verbindungsvektor zum naechsten streckenteil
		return myConnection;
	}
	
	public function set connection(cobj:Vector ):Void
	{
		// verbindungsvektor zum naechsten streckenteil
		myConnection = cobj;
	}
	
	public function get polygon():Polygon
	{
		// polygon des streckenstuecks
		return myPolygon;
	}
}