/*
 * Generated by ASDT
*/

class com.adgamewonderland.duden.sudoku.game.beans.Content {

	public static var CONTENT_EMPTY:Number = -1;

	private var id:Number;

	private var character:String;

	public function Content(id:Number, character:String ) {
		this.id = id;
		this.character = character;
	}

	public function toString():String
	{
		return ("Content: " + getId());
	}

	public function equals(c:Content ):Boolean
	{
		return (c.getId() == this.getId());
	}

	public function getId():Number {
		return id;
	}

	public function setId(id:Number):Void {
		this.id = id;
	}

	public function getCharacter():String {
		return character;
	}

	public function setCharacter(character:String):Void {
		this.character = character;
	}

}