/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.agw.interfaces.ITimeUI;
import com.adgamewonderland.agw.util.Timer;

class com.adgamewonderland.aldi.mahjong.ui.ClockUI extends MovieClip implements ITimeUI {
	
	private var dial_mc:MovieClip;
	
	public function ClockUI() {
	}
	
	public function showTime(tobj:Timer ):Void
	{
		// prozent
		var percent:Number = tobj.getPercent();
		// frame
		var frame:Number = Math.ceil(percent / 100 * dial_mc._totalframes);
		// hinspringen
		dial_mc.gotoAndStop(frame);
	}
}