/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.aldi.mahjong.ui.ClockUI;

class com.adgamewonderland.aldi.mahjong.ui.DisplayUI extends MovieClip {
	
	private var clock_mc:ClockUI;
	
	private var score_txt:TextField;
	
	private var moves_txt:TextField;
	
	private var stones_txt:TextField;
	
	public function DisplayUI() {
		// textfelder linksbuendig
		score_txt.autoSize = "left";
		moves_txt.autoSize = "left";
		stones_txt.autoSize = "left";
	}
	
	public function getClock():ClockUI
	{
		// zurueck geben
		return clock_mc;
	}
	
	public function showScore(score:Number ):Void
	{
		// anzeigen
		score_txt.text = String(score);
	}
	
	public function showMoves(moves:Number ):Void
	{
		// anzeigen
		moves_txt.text = String(moves);	
	}
	
	public function showStones(stones:Number ):Void
	{
		// anzeigen
		stones_txt.text = String(stones);	
	}
}