/* 
 * Generated by ASDT 
*/ 

class com.adgamewonderland.aldi.mahjong.ui.InstructionsUI extends MovieClip {
	
	private var animation_mc:MovieClip;
	
	private var start_btn:Button;
	
	private var tellafriend_btn:Button;
	
	private var highscore_btn:Button;
	
	public function InstructionsUI() {
		// einblenden
		showInstructions(true);
		// start button ausblenden
		start_btn._visible = false;
	}
	
	public function init():Void
	{
		// start button einblenden
		start_btn._visible = true;
		// starten
		start_btn.onRelease = function() {
			this._parent.onStart();
		}
		// tellafriend
		tellafriend_btn.onRelease = function() {
			this._parent.onTellafriend();
		}
		// highscore
		highscore_btn.onRelease = function() {
			this._parent.onHighscore();
		}
	}
	
	public function onStart():Void
	{
		// start button ausblenden
		start_btn._visible = false;
		// animation ausblenden
		animation_mc.gotoAndPlay("frOut");
	}
	
	public function onClose():Void
	{
		// ausblenden
		showInstructions(false);
		// spiel starten
		_parent.startGame();
	}
	
	public function onTellafriend():Void
	{
		// gameid an javascript uebergeben
		getURL("javascript:showTellafriend(" + _parent.getReportingProcessor().getGameid() + ");");
	}
	
	public function onHighscore():Void
	{
		// highscoreliste laden
		_parent.highscore_mc.getHighscore(false, 0);
	}
	
	public function showInstructions(bool:Boolean ):Void
	{
		// ein- / ausblenden
		_visible = bool;
	}
}