/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.duden.sudoku.game.beans.*;

interface com.adgamewonderland.duden.sudoku.game.interfaces.IFieldListener {
	
	public function onContentChanged(field:Field, oldcontent:Content ):Void;
	
	public function onGuessChanged(field:Field, guess:Content, added:Boolean ):Void;
	
	public function onContainerFinished(container:ContainerImpl ):Void;
}