/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.agw.math.Point;

class com.adgamewonderland.dhl.adventskalender.beans.Game {
	
	private var id:Number;
	
	private var name:String;
	
	private var file:String;
	
	private var scale:Number;
	
	private var position:Point;
	
	private var width:Number;
	
	private var height:Number;
	
	public function Game(id:Number, name:String, file:String, scale:Number, xpos:Number, ypos:Number, width:Number, height:Number ) {
		this.id = id;
		this.name = name;
		this.file = file;
		this.scale = scale;
		this.position = new Point(xpos, ypos);
		this.width = width;
		this.height = height;
	}

	public function getId():Number {
		return id;
	}

	public function getName():String {
		return name;
	}
	
	public function getFile():String {
		return file;
	}

	public function getScale():Number {
		return scale;
	}

	public function getPosition():Point {
		return position;
	}
	public function getHeight():Number {
		return height;
	}

	public function getWidth():Number {
		return width;
	}

}