/* 
 * Generated by ASDT 
*/ 

class com.adgamewonderland.aldi.ecard.ui.BackgroundUI extends MovieClip {
	
	public function BackgroundUI() {
		
	}
	
	public function setBackground(num:Number ):Void
	{
		gotoAndStop(num);
	}
	
	public function getBackground():Number
	{
		return _currentframe;
	}
}