/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.aldi.ecard.ui.*;

class com.adgamewonderland.aldi.ecard.ui.InstructionsUI extends MovieClip {
	
	private var close_btn:Button;
	
	public function InstructionsUI() {
		// ausblenden
		showInstructions(false);
		// schliessen
		close_btn.onRelease = function() {
			this._parent.onClose();
		}
	}
	
	public function onClose():Void
	{
		// ausblenden
		showInstructions(false);
	}
	
	public function showInstructions(bool:Boolean ):Void
	{
		// ein- / ausblenden
		_visible = bool;
	}
}