/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.aldi.ecard.ui.PaletteTextUI;

class com.adgamewonderland.aldi.ecard.ui.PaletteFontUI extends MovieClip {
	
	private var _myFont:String;
	
	private var myPaletteUI:PaletteTextUI;
	
	public function PaletteFontUI()
	{
		myPaletteUI = PaletteTextUI(_parent);
	}
	
	public function onRelease():Void
	{
		myPaletteUI.onChangeFont(_myFont);
	}
}