/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.aldi.ecard.ui.ItemTextUI;
import com.adgamewonderland.aldi.ecard.ui.PaletteColorUI;
import com.adgamewonderland.aldi.ecard.ui.PaletteFontUI;
import com.adgamewonderland.aldi.ecard.ui.PaletteUI;

class com.adgamewonderland.aldi.ecard.ui.PaletteTextUI extends PaletteUI {
	
	private var myItemUI:ItemTextUI;
	
	private var color1_mc:PaletteColorUI;
	
	private var color2_mc:PaletteColorUI;
	
	private var color3_mc:PaletteColorUI;
	
	private var color4_mc:PaletteColorUI;
	
	private var font1_mc:PaletteFontUI;
	
	private var font2_mc:PaletteFontUI;
	
	public function PaletteTextUI()
	{
		super();
		
		myItemUI = ItemTextUI(_parent);
	}
	
	public function onChangeColor(color:Number ):Void
	{
		myItemUI.setColor(color);
	}
	
	public function onChangeFont(font:String ):Void
	{
		myItemUI.setFont(font);
	}
}