/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.aldi.ecard.ui.ToolbarComposeUI;
import com.adgamewonderland.aldi.ecard.ui.ToolbarReceiveUI;
import com.adgamewonderland.aldi.ecard.ui.ToolbarSendUI;

class com.adgamewonderland.aldi.ecard.ui.ToolbarUI extends MovieClip {
	
	public static var MODE_COMPOSE:Number = 1;
	
	public static var MODE_SEND:Number = 2;
	
	public static var MODE_RECEIVE:Number = 3;
	
	public static var MODE_SENT:Number = 4;
	
	private var mode:Number;
	
	private var compose_mc:ToolbarComposeUI;
	
	private var send_mc:ToolbarSendUI;
	
	private var receive_mc:ToolbarReceiveUI;
	
	public function ToolbarUI() {
		watch("mode", onSetMode, null);
	}
	
	public function getMode():Number {
		return mode;
	}

	public function setMode(mode:Number):Void {
		this.mode = mode;
	}
	
	public function getReceive():ToolbarReceiveUI
	{
		return receive_mc;
	}
	
	private function onSetMode(prop:String, oldval:Number, newval:Number ):Number
	{
		// hinspringen
		switch (newval) {
			// compose
			case MODE_COMPOSE :
				
				gotoAndStop("frCompose");
				break;	
			// send
			case MODE_SEND :
				// stage nicht editierbar
				_global.EcardUI.getStage().setEditable(false);
			
				gotoAndStop("frSend");
				break;
			// receive
			case MODE_RECEIVE :
				
				gotoAndStop("frReceive");
				break;
			// sent
			case MODE_SENT :
			
				gotoAndStop("frSent");
				break;
		}
		// neuen wert setzen
		return newval;
	}

}