/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.aldi.ecard.beans.*;

import com.adgamewonderland.aldi.ecard.ui.*;

class com.adgamewonderland.aldi.ecard.ui.ToolbarComposeItemTextUI extends MovieClip {
	
	public function ToolbarComposeItemTextUI() {
	}
	
	public function onRelease():Void
	{
		// stage
		var stage:StageUI = _global.EcardUI.getStage()
		// neues item
		var item:ItemText = new ItemText(null);
		// auf buehne bringen
		stage.addItem(item);
	}
	
}