/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.aldi.ecard.beans.*;

class com.adgamewonderland.aldi.ecard.ui.ToolbarReceiveUI extends MovieClip {
	
	private var sendername_txt:TextField;
	
	private var senderemail_txt:TextField;
	
	private var receivername_txt:TextField;
	
	private var receiveremail_txt:TextField;
	
	private var compose_btn:Button;
	
	public function ToolbarReceiveUI() {
		// neue ecard verfassen
		compose_btn.onRelease = function() {
			this._parent.onCompose();
		}
	}
	
	public function showUsers(sender:User, receiver:User ):Void
	{
		// name
		sendername_txt.text = sender.getName();
		// email
		senderemail_txt.text = sender.getEmail();
		// name
		receivername_txt.text = receiver.getName();
		// email
		receiveremail_txt.text = receiver.getEmail();
	}
	
	public function onCompose():Void
	{
		// neue ecard
		_global.EcardUI.initEcard(null, null);
	}
}