/* 
 * Generated by ASDT 
*/ 

/*
klasse:			InfoboxUI
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			blaupunkt
erstellung: 		15.06.2005
zuletzt bearbeitet:	15.06.2005
durch			gj
status:			in bearbeitung
*/

class com.adgamewonderland.blaupunkt.dtmracing.ui.InfoboxUI extends MovieClip {
	
	public function initInfobox(status:Number ):Void { trace("initInfobox: " + this); }
	
	public function onChangeTrack(tid:Number ):Void { trace("onChangeTrack: " + this); }
}