/* 
 * Generated by ASDT 
*/ 

/*
klasse:			InfoboxMainUI
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			blaupunkt
erstellung: 		15.06.2005
zuletzt bearbeitet:	26.06.2005
durch			gj
status:			in bearbeitung
*/

import com.adgamewonderland.blaupunkt.dtmracing.challenge.*;

import com.adgamewonderland.blaupunkt.dtmracing.ui.*;

class com.adgamewonderland.blaupunkt.dtmracing.ui.InfoboxMainUI extends InfoboxUI {
	
	private var statistics_mc:UserStatisticUI;
	
	private var infolist1_mc:InfoListUI;
	
	private var infolist2_mc:InfoListUI;
	
	private var infolist3_mc:InfoListUI;
	
	public function InfoboxMainUI()
	{
		// vererbung
		super.constructor.apply(super, arguments);
		// alle ausblenden
		statistics_mc._visible = infolist1_mc._visible = infolist2_mc._visible = infolist3_mc._visible = false;
	}
	
	public function initInfobox(status:Number ):Void
	{
		// statistik challenger laden
		statistics_mc.init();
		// infolisten laden
		infolist1_mc.init();
		infolist2_mc.init();
		infolist3_mc.init();
		// abspielen verfolgen
		onEnterFrame = function() {
			// nacheinander einblenden
			if (_currentframe == _totalframes - 4) statistics_mc._visible = true;
			if (_currentframe == _totalframes - 3) infolist1_mc._visible = true;
			if (_currentframe == _totalframes - 2) infolist2_mc._visible = true;
			if (_currentframe == _totalframes - 1) infolist3_mc._visible = true;
			if (_currentframe == _totalframes - 0) delete(onEnterFrame);
		};
		// abspielen
		play();
	}
	
	public function onChangeTrack(tid:Number ):Void
	{
		// statistik anzeigen lassen
		statistics_mc.showUserTrackStatistic(tid);
	}
	
	public function getUserStatisticUI():UserStatisticUI
	{
		return statistics_mc;
	}
}