/* 
 * Generated by ASDT 
*/ 

/*
klasse:			MetaInstructionsUI
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			blaupunkt
erstellung: 		25.06.2005
zuletzt bearbeitet:	25.06.2005
durch			gj
status:			in bearbeitung
*/

import com.adgamewonderland.agw.util.*;

import com.adgamewonderland.blaupunkt.dtmracing.ui.*;

class com.adgamewonderland.blaupunkt.dtmracing.ui.MetaInstructionsUI extends MetaContentUI {
	
	private var instructions_mc:MovieClip;
	
	private var scrollbar_mc:ScrollbarUI;
	
	public function MetaInstructionsUI()
	{
		// vererbung
		super();
	}
	
	public function init():Void
	{
		// vererbung
		super.init();
		// scrollbar initialisieren
		scrollbar_mc.setScrollTarget(instructions_mc);
	}
}