/* 
 * Generated by ASDT 
*/ 

/*
klasse:			MetaContentUI
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			blaupunkt
erstellung: 		25.06.2005
zuletzt bearbeitet:	25.06.2005
durch			gj
status:			in bearbeitung
*/

import com.adgamewonderland.agw.util.*;

import com.adgamewonderland.blaupunkt.dtmracing.ui.*;

class com.adgamewonderland.blaupunkt.dtmracing.ui.MetaContentUI extends MovieClip {
	
	private var meta_transition_mc:MovieClip;
	
	private var close_btn:Button;
	
	public function MetaContentUI()
	{
		// abspielen verfolgen
		var follower:TimelineFollower = new TimelineFollower(this, "init");
		// abspielen verfolgen
		onEnterFrame = function() {
			follower.followTimeline();
		}
	}
	
	public function init():Void
	{
		// metal hochfahren
		meta_transition_mc.showMetal(true);
		// button schliessen
		close_btn.onRelease = function() {
			this._parent.closeContent();
		};
	}
	
	public function closeContent():Void
	{
		// metal runterfahren
		meta_transition_mc.showMetal(false);
		// abspielen verfolgen
		var follower:TimelineFollower = new TimelineFollower(this, "onContentClosed");
		// abspielen verfolgen
		onEnterFrame = function() {
			follower.followTimeline();
		}
		// abspielen
		gotoAndPlay("frClose");
	}
	
	public function onContentClosed():Void
	{
		// metanavi schliessen
		this._parent.showContent("init", false);
	}
}