/* 
 * Generated by ASDT 
*/ 

/*
klasse:			NavigationUI
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			blaupunkt
erstellung: 		15.06.2005
zuletzt bearbeitet:	28.06.2005
durch			gj
status:			in bearbeitung
*/

class com.adgamewonderland.blaupunkt.dtmracing.ui.NavigationUI extends MovieClip {
	
	private static var TIME_NAVIGATE:Number = 50;
	
	private var myButtons:Array;
	
	public function NavigationUI()
	{
		// navigations buttons
		myButtons = new Array();
	}
	
	public function setButtonsActive(bool:Boolean ):Void
	{
		// schleife ueber alle buttons
		for (var i:String in myButtons) {
			// de- / aktivieren
			myButtons[i]._enabled = bool;
		}
	}
	
	public function setButtonsVisible(bool:Boolean ):Void
	{
		// schleife ueber alle buttons
		for (var i:String in myButtons) {
			// ein- / ausblenden
			myButtons[i]._visible = bool;
		}
	}
	
	private function navigate(frame:String, pause:Number, target:String, method:String, args:Array ):Void
	{
		// hinspringen
		gotoAndStop(frame);
		// funktion zur uebergabe der parameter an ziel
		var invokeMethod = function(target:Object ) {
			// uebergeben
			target[method](args[0]);
			// interval loeschen
			clearInterval(interval);
		};
		// nach pause aufrufen
		var interval:Number = setInterval(invokeMethod, pause, this[target]);
	}
}