/* 
 * Generated by ASDT 
*/ 

/*
klasse:			RaceResultUI
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			blaupunkt
erstellung: 		19.06.2005
zuletzt bearbeitet:	19.06.2005
durch			gj
status:			in bearbeitung
*/

import com.adgamewonderland.agw.util.*;

import com.adgamewonderland.blaupunkt.dtmracing.challenge.*;

class com.adgamewonderland.blaupunkt.dtmracing.ui.RaceResultUI extends MovieClip {
	
	private var _myMode:Number;
	
	private var racetime_txt:TextField;
	
	private var lapresult1_txt:TextField;
	
	private var lapresult2_txt:TextField;
	
	private var lapresult3_txt:TextField;
	
	public function RaceResultUI()
	{
		// rennzeit linksbuendig
		racetime_txt.autoSize = "left";
		// rundenzeiten linksbuendig
		lapresult1_txt.autoSize = lapresult2_txt.autoSize = lapresult3_txt.autoSize = "left";
		// ergebnisse anzeigen
		showRaceResult(_myMode);
	}
	
	private function showRaceResult(mode:Number ):Void
	{
		// rennzeit
		var racetime:Number = ChallengeController.getInstance().getRacetime(mode);
		// anzeigen
		racetime_txt.text = "Rennzeit: " + TimeFormater.getMinutesSecondsMilliseconds(racetime);
		// rundenzeiten
		var lapresults:Array = ChallengeController.getInstance().getLapresults(_myMode);
		// schleife ueber rundenzeiten
		for (var i:String in lapresults) {
			// aktuelle rundenzeit
			var lapresult:ChallengeLapresult = lapresults[i];
			// anzeigen
			this["lapresult" + lapresult.getLap() + "_txt"].text = "Lap" + lapresult.getLap() + ": " + TimeFormater.getMinutesSecondsMilliseconds(lapresult.getLaptime());
		}
	}
	
}