/* 
 * Generated by ASDT 
*/ 

import com.adgamewonderland.agw.interfaces.ITimeUI;
import com.adgamewonderland.agw.util.Timer;
import com.adgamewonderland.aldi.pipeman.beans.Level;
import com.adgamewonderland.aldi.pipeman.beans.Pipeman;

class com.adgamewonderland.aldi.pipeman.ui.DisplayUI extends MovieClip implements ITimeUI {
	
	private var level_txt:TextField;
	
	private var score_txt:TextField;
	
	private var time_txt:TextField;
	
	public function DisplayUI() {
		// registrieren
		Pipeman.getInstance().addListener(this);
	}
	
	public function onLoad():Void
	{
		// textfelder ausrichten
		level_txt.autoSize = "right";
		score_txt.autoSize = "right";
		time_txt.autoSize = "left";
	}
	
	public function onLevelStarted(level:Level, score:Number, timer:Timer ):Void
	{
		// level anzeigen
		showLevel(level.getId());
		// score anzeigen
		showScore(score);
		// bei timer registrieren
		timer.addUI(this);
	}
	
	public function onScoreUpdated(score:Number ):Void
	{
		// score anzeigen
		showScore(score);
	}
	
	public function showLevel(level:Number ):Void
	{
		// anzeigen
		level_txt.text = String(level);	
	}
	
	public function showScore(score:Number ):Void
	{
		// anzeigen
		score_txt.text = String(score);
	}
	
	public function showTime(tobj:Timer ):Void
	{
		// sekunden
		var seconds:Object = tobj.getSeconds();
		// uebrig
		var left:Number = seconds["left"];
		// formatieren
		var ftime:String = Timer.getFormattedTime(left, ":");
		// nur minuten und sekunden
		ftime = ftime.substring(ftime.indexOf(":") + 1, ftime.length);
		// anzeigen
		time_txt.text = ftime;
	}
}