/* 
 * Generated by ASDT 
*/ 

/*
klasse:			Prize
autor: 			gerd jungbluth, adgame-wonderland
email:			gerd.jungbluth@adgame-wonderland.de
kunde:			ssk ddorf
erstellung: 		09.09.2005
zuletzt bearbeitet:	09.09.2005
durch			gj
status:			in bearbeitung
*/

class com.adgamewonderland.sskddorf.slotmachine.beans.Prize {
	
	private var id:Number;
	
	private var type:String;
	
	private var description:String;
	
	private var sponsorid:Number;
	
	public function Prize()
	{
		// id
		this.id = 0;
		// type
		this.type = "";
		// description
		this.description = "";
		// sponorid
		this.sponsorid = 0;
	}
	
	public function getSponsorid():Number {
		return sponsorid;
	}

	public function setSponsorid(sponsorid:Number):Void {
		this.sponsorid = sponsorid;
	}

	public function getId():Number {
		return id;
	}

	public function setId(id:Number):Void {
		this.id = id;
	}

	public function getDescription():String {
		return description;
	}

	public function setDescription(description:String):Void {
		this.description = description;
	}

	public function getType():String {
		return type;
	}

	public function setType(type:String):Void {
		this.type = type;
	}

}