/*
 * Generated by ASDT
*/

class com.adgamewonderland.sskddorf.slotmachine.beans.User {

	private var uid:Number;

	private var salutation:String;

	private var firstname:String;

	private var lastname:String;

	private var street:String;

	private var postcode:String;

	private var city:String;

	private var email:String;

	private var password:String;

	private var optin:Boolean;

	public function User() {
		// fuer remoting registrieren
		Object.registerClass("com.adgamewonderland.sskddorf.slotmachine.beans.User", User);
	}

	public function getUid():Number {
		return uid;
	}

	public function setUid(uid:Number):Void {
		this.uid = uid;
	}

	public function getSalutation():String {
		return salutation;
	}

	public function setSalutation(salutation:String):Void {
		this.salutation = salutation;
	}

	public function getFirstname():String {
		return firstname;
	}

	public function setFirstname(firstname:String):Void {
		this.firstname = firstname;
	}

	public function getLastname():String {
		return lastname;
	}

	public function setLastname(lastname:String):Void {
		this.lastname = lastname;
	}

	public function getStreet():String {
		return street;
	}

	public function setStreet(street:String):Void {
		this.street = street;
	}

	public function getPostcode():String {
		return postcode;
	}

	public function setPostcode(postcode:String):Void {
		this.postcode = postcode;
	}

	public function getCity():String {
		return city;
	}

	public function setCity(city:String):Void {
		this.city = city;
	}

	public function getEmail():String {
		return email;
	}

	public function setEmail(email:String):Void {
		this.email = email;
	}

	public function getPassword():String {
		return password;
	}

	public function setPassword(password:String):Void {
		this.password = password;
	}

	public function getOptin():Boolean {
		return optin;
	}

	public function setOptin(optin:Boolean):Void {
		this.optin = optin;
	}

	public function toString() : String {
		var ret:String = "com.adgamewonderland.sskddorf.slotmachine.beans.User";
		for (var i in this) {
			ret += "\n" + i + ": " + this[i];
		}
		return ret;
	}

}